package directlauncher

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/kshrkznr/code-toolkit/go/internal/distribution"
	ctkplatform "github.com/kshrkznr/code-toolkit/go/internal/platform"
)

const marker = "Generated by CTK. This file may be regenerated by Build or Apply."

type Result struct {
	Path    string
	Changed bool
	Warning string
}

// Generate materializes the readable command-form Direct Launcher selected by
// the initial Go Build Strategy. Unknown existing files are preserved.
func Generate(dist distribution.Distribution) (Result, error) {
	definition, err := ctkplatform.Lookup(dist.Recipe.Platform)
	if err != nil {
		return Result{}, err
	}
	command := definition.Command
	if strings.EqualFold(dist.Recipe.OS, "windows") && !safeWindowsCommand(command) {
		return Result{}, fmt.Errorf("unsafe Windows Platform command %q", command)
	}
	name, content, mode, supported := render(dist, command)
	if !supported {
		return Result{Warning: "Direct Launcher is unsupported for Recipe OS: " + dist.Recipe.OS}, nil
	}
	if strings.EqualFold(name, overrideName(dist.Recipe.OS)) {
		return Result{Warning: "Direct Launcher name conflicts with Launch Override: " + name}, nil
	}
	target := filepath.Join(dist.Path, name)
	if info, err := os.Lstat(target); err == nil {
		if info.IsDir() || info.Mode()&os.ModeSymlink != 0 {
			return Result{Path: target, Warning: "preserved unknown Direct Launcher target: " + target}, nil
		}
		existing, readErr := os.ReadFile(target)
		if readErr != nil {
			return Result{}, fmt.Errorf("read Direct Launcher %s: %w", target, readErr)
		}
		if !managed(existing) {
			return Result{Path: target, Warning: "preserved unknown Direct Launcher file: " + target}, nil
		}
		if string(existing) == content && info.Mode().Perm() == mode {
			return Result{Path: target}, nil
		}
	} else if !os.IsNotExist(err) {
		return Result{}, fmt.Errorf("inspect Direct Launcher %s: %w", target, err)
	}

	if err := writeAtomic(target, []byte(content), mode); err != nil {
		return Result{}, err
	}
	return Result{Path: target, Changed: true}, nil
}

func overrideName(recipeOS string) string {
	if strings.EqualFold(recipeOS, "windows") {
		return "run.cmd"
	}
	return "run.sh"
}

func render(dist distribution.Distribution, command string) (string, string, os.FileMode, bool) {
	switch strings.ToLower(dist.Recipe.OS) {
	case "macos", "darwin", "linux":
		return dist.Name, unixScript(command), 0o755, true
	case "windows":
		return dist.Name + ".cmd", windowsScript(command), 0o644, true
	default:
		return "", "", 0, false
	}
}

func unixScript(platform string) string {
	return `#!/usr/bin/env bash
# ` + marker + `
set -euo pipefail

BASE_DIR="$(cd "$(dirname "$0")" && pwd)"

if [[ -e "$BASE_DIR/run.sh" ]]; then
    exec "$BASE_DIR/run.sh" "$@"
fi

PLATFORM_BIN="$(command -v ` + shellQuote(platform) + `)" || {
    echo "platform command not found: ` + shellMessage(platform) + `" >&2
    exit 1
}

exec "$PLATFORM_BIN" \
  --user-data-dir "$BASE_DIR/.data" \
  --extensions-dir "$BASE_DIR/.ext" \
  "$@"
`
}

func windowsScript(platform string) string {
	return `@echo off
rem ` + marker + `
setlocal
set "BASE_DIR=%~dp0"

if exist "%BASE_DIR%run.cmd" (
    call "%BASE_DIR%run.cmd" %*
    exit /b %ERRORLEVEL%
)

where ` + platform + ` >nul 2>nul
if errorlevel 1 (
    echo platform command not found: ` + platform + ` 1>&2
    exit /b 1
)

` + platform + ` --user-data-dir "%BASE_DIR%.data" --extensions-dir "%BASE_DIR%.ext" %*
exit /b %ERRORLEVEL%
`
}

func managed(content []byte) bool {
	value := string(content)
	if strings.Contains(value, marker) {
		return true
	}
	// Recognize the exact responsibility of the historical CTK-generated
	// wrapper so Apply can migrate it without treating arbitrary scripts as
	// disposable.
	return strings.Contains(value, `exec "$BASE_DIR/run.sh" "$@"`) ||
		(strings.Contains(value, `set BASE_DIR=%~dp0`) && strings.Contains(value, `bash "%BASE_DIR%run.sh" %*`))
}

func writeAtomic(target string, content []byte, mode os.FileMode) error {
	if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
		return err
	}
	temporary, err := os.CreateTemp(filepath.Dir(target), ".launcher-*")
	if err != nil {
		return fmt.Errorf("create Direct Launcher staging: %w", err)
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if _, err = temporary.Write(content); err == nil {
		err = temporary.Chmod(mode)
	}
	if closeErr := temporary.Close(); err == nil {
		err = closeErr
	}
	if err != nil {
		return fmt.Errorf("write Direct Launcher staging: %w", err)
	}

	backup := ""
	hadTarget := false
	if _, statErr := os.Lstat(target); statErr == nil {
		placeholder, createErr := os.CreateTemp(filepath.Dir(target), ".launcher-backup-*")
		if createErr != nil {
			return fmt.Errorf("create Direct Launcher backup path: %w", createErr)
		}
		backup = placeholder.Name()
		if closeErr := placeholder.Close(); closeErr != nil {
			return closeErr
		}
		if removeErr := os.Remove(backup); removeErr != nil {
			return removeErr
		}
		if err := os.Rename(target, backup); err != nil {
			return fmt.Errorf("stage existing Direct Launcher: %w", err)
		}
		hadTarget = true
	} else if !os.IsNotExist(statErr) {
		return statErr
	}
	if err := os.Rename(temporaryPath, target); err != nil {
		if hadTarget {
			_ = os.Rename(backup, target)
		}
		return fmt.Errorf("publish Direct Launcher: %w", err)
	}
	if hadTarget {
		_ = os.Remove(backup)
	}
	return nil
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", `'\''`) + "'"
}

func shellMessage(value string) string {
	return strings.ReplaceAll(strings.ReplaceAll(value, "\\", "\\\\"), `"`, `\"`)
}

func safeWindowsCommand(value string) bool {
	if value == "" {
		return false
	}
	for _, character := range value {
		if character >= 'a' && character <= 'z' || character >= 'A' && character <= 'Z' || character >= '0' && character <= '9' || strings.ContainsRune("._-", character) {
			continue
		}
		return false
	}
	return true
}
