package main

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestGenerateAppendAndVerifyModesShareOneBundle(t *testing.T) {
	repositoryRoot, err := filepath.Abs(filepath.Join("..", "..", ".."))
	if err != nil {
		t.Fatal(err)
	}
	temporary := t.TempDir()
	archive := filepath.Join(temporary, "bundle.zip")
	metadata := []string{"-version", "v0.4.0", "-revision", "abc1234", "-tag", "v0.4.0"}
	var generated bytes.Buffer
	args := append([]string{"-root", repositoryRoot, "-output", archive}, metadata...)
	if err := run(args, &generated); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(generated.String(), "content-sha256: ") {
		t.Fatalf("generation output = %q", generated.String())
	}

	executable := filepath.Join(temporary, "ctk")
	if err := os.WriteFile(executable, []byte("mock executable\n"), 0o755); err != nil {
		t.Fatal(err)
	}
	expectations := []string{"-expect-version", "v0.4.0", "-expect-revision", "abc1234", "-expect-tag", "v0.4.0"}
	var appended bytes.Buffer
	args = append([]string{"-input", archive, "-append-to", executable}, expectations...)
	if err := run(args, &appended); err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(appended.String(), "appended: "+executable) {
		t.Fatalf("append output = %q", appended.String())
	}

	var verified bytes.Buffer
	args = append([]string{"-verify-executable", executable}, expectations...)
	if err := run(args, &verified); err != nil {
		t.Fatal(err)
	}
	for _, expected := range []string{"ctk-version: v0.4.0", "source-revision: abc1234", "release-tag: v0.4.0", "definition-sha256: ", "content-sha256: "} {
		if !strings.Contains(verified.String(), expected) {
			t.Fatalf("verification output does not contain %q: %s", expected, verified.String())
		}
	}
	if err := run([]string{"-verify-executable", executable, "-expect-revision", "different"}, &bytes.Buffer{}); err == nil {
		t.Fatal("verification accepted mismatched provenance")
	}
}

func TestRunRequiresOneValidMode(t *testing.T) {
	for _, args := range [][]string{nil, {"-input", "bundle.zip"}, {"-output", "bundle.zip", "-input", "other.zip"}, {"-verify-executable", "ctk", "-append-to", "other"}} {
		if err := run(args, &bytes.Buffer{}); err == nil {
			t.Fatalf("run(%v) accepted invalid mode", args)
		}
	}
}
